In [1]:
import networkx as nx
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from matplotlib import rcParams
from matplotlib.ticker import MultipleLocator, FormatStrFormatter

In [2]:
plt.rcParams.update({'font.size': 30, 'font.family': 'Arial', 'mathtext.fontset': 'stix'})
plt.rcParams['figure.dpi'] =  300

TickSize = 88
LegendSize = 78
# heatmapFontSize = 40
subplotTitleSize = 98
Labelpad = 25

In [3]:
def lighten_color(color, amount=0.5):
    import matplotlib.colors as mc
    import colorsys
    try:
        c = mc.cnames[color]
    except:
        c = color
    c = colorsys.rgb_to_hls(*mc.to_rgb(c))
    return colorsys.hls_to_rgb(c[0], 1 - amount * (1 - c[1]), c[2])

def SyntheticBar(Ax, prob_type, cost, tag, width):
    val=0.5
    colors = {'Absolute':lighten_color('blueviolet', val),'HDA':lighten_color('skyblue', 1.0),'HBA':lighten_color('orange', 1),
              'HCA':lighten_color('k', val),'HPRA':lighten_color('magenta', val),'Tarjan':lighten_color('blue', 0.5),
              'FINDER':lighten_color('teal', 0.5),'ND-GRL':lighten_color('red', 1.0)}
#     syn = pd.read_csv('../data/%s_synthetic_%s_cost.csv'%(prob_type, cost))
        
#     s = syn.values[:,1:]
#     s = np.array([[li.split('+') for li in l] for l in s], dtype = np.float32)

    if prob_type == 'CN' and cost == 'unit':
#         s = np.array([[[0.09],[0.52],[2.17],[15.62],[49.59],[165.37]],
#                   [[0.009],[0.01],[0.03],[0.1],[0.31],[0.57]],
#                   [[0.06],[0.35],[2.01],[9.55],[26.21],[54.29]],
#                   [[0.06],[0.36],[2.1],[9.52],[26.3],[54.35]],
#                   [[0.13],[0.42],[1.46],[3.68],[7.09],[11.47]],
#                   [[0.01],[0.02],[0.04],[0.16],[0.47],[0.87]],
#                   [[0.19],[0.3],[0.51],[0.56],[0.73],[1.23]],
#                   [[0.39],[0.73],[1.25],[1.5],[1.97],[2.73]]], dtype = np.float32)
        
        s = np.array([[[2.17],[15.62],[49.59],[165.37]],
                  [[0.03],[0.1],[0.31],[0.57]],
                  [[2.01],[9.55],[26.21],[54.29]],
                  [[2.1],[9.52],[26.3],[54.35]],
                  [[1.46],[3.68],[7.09],[11.47]],
                  [[0.04],[0.16],[0.47],[0.87]],
                  [[0.51],[0.56],[0.73],[1.23]],
                  [[1.25],[1.5],[1.97],[2.73]]], dtype = np.float32)
        
        
    elif prob_type == 'CN' and cost == 'degree':
#         s = np.array([[[0.09],[0.41],[3.48],[22.03],[70.89],[160.85]],
#                   [[0.009],[0.01],[0.04],[0.14],[0.31],[0.51]],
#                   [[0.06],[0.3],[2.42],[10.26],[26.91],[48.52]],
#                   [[0.06],[0.32],[2.45],[10.24],[27.01],[48.41]],
#                   [[0.13],[0.39],[1.5],[3.91],[7.3],[10.15]],
#                   [[0.01],[0.01],[0.07],[0.21],[0.48],[0.76]],
#                   [[0.2],[0.31],[0.62],[0.59],[0.78],[1.06]],
#                   [[0.51],[0.68],[1.29],[1.55],[2.24],[2.85]]], dtype = np.float32)
        
        s = np.array([[[3.48],[22.03],[70.89],[160.85]],
                  [[0.04],[0.14],[0.31],[0.51]],
                  [[2.42],[10.26],[26.91],[48.52]],
                  [[2.45],[10.24],[27.01],[48.41]],
                  [[1.5],[3.91],[7.3],[10.15]],
                  [[0.07],[0.21],[0.48],[0.76]],
                  [[0.62],[0.59],[0.78],[1.06]],
                  [[1.29],[1.55],[2.24],[2.85]]], dtype = np.float32)
        
    elif prob_type == 'ND' and cost == 'unit':
#         s = np.array([[[0.07],[0.32],[2.21],[8.59],[26.67],[55.12]],
#                   [[0.009],[0.01],[0.03],[0.06],[0.14],[0.21]],
#                   [[0.05],[0.28],[2.01],[8.21],[22.33],[47.77]],
#                   [[0.05],[0.3],[2.12],[8.64],[23.08],[50.38]],
#                   [[0.13],[0.42],[1.47],[3.73],[6.9],[11.2]],
#                   [[0.009],[0.01],[0.04],[0.11],[0.25],[0.37]],
#                   [[0.2],[0.3],[0.54],[0.65],[0.65],[0.86]],
#                   [[0.4],[0.56],[1.26],[1.34],[1.77],[2.34]]], dtype = np.float32)
        
        s = np.array([[[2.21],[8.59],[26.67],[55.12]],
                  [[0.03],[0.06],[0.14],[0.21]],
                  [[2.01],[8.21],[22.33],[47.77]],
                  [[2.12],[8.64],[23.08],[50.38]],
                  [[1.47],[3.73],[6.9],[11.2]],
                  [[0.04],[0.11],[0.25],[0.37]],
                  [[0.54],[0.65],[0.65],[0.86]],
                  [[1.26],[1.34],[1.77],[2.34]]], dtype = np.float32)
        
    else:
#         s = np.array([[[0.12],[0.43],[1.25]],
#                   [[0.009],[0.01],[0.02]],
#                   [[0.2],[1.15],[5.45]],
#                   [[0.19],[0.83],[2.85]],
#                   [[0.31],[0.62],[1.12]],
#                   [[0.009],[0.01],[0.01]],
#                   [[0.23],[0.19],[0.16]],
#                   [[0.79],[1.02],[1.57]]], dtype = np.float32)
        
        s = np.array([[[0.43],[1.25]],
                  [[0.01],[0.02]],
                  [[1.15],[5.45]],
                  [[0.83],[2.85]],
                  [[0.62],[1.12]],
                  [[0.01],[0.01]],
                  [[0.19],[0.16]],
                  [[1.02],[1.57]]], dtype = np.float32)

    
#     X = np.array([-1,0,1,2.05,3.2,4.35])
    if prob_type == 'ND' and cost == 'degree':
#         X = np.array([-0.6,1.05,2.5])
        X = np.array([0.225,1.775])
    else:
#         X = np.array([-1,0.45,1.9,3.35,4.8,6.25])
        X = np.array([-0.42,1.61,3.64,5.67])
    
    methods = ['Absolute', 'HDA', 'HBA', 'HCA', 'HPRA', 'Tarjan', 'FINDER', 'ND-GRL']
#     if prob_type == 'CN':
#         methods = ['HDA','CI','RatioCut','FINDER']
#     else:
#         methods = ['HDA','CI','MinSum','GND','FINDER']
        
#     xtick_labels = ['30-50', '50-100', '100-200', '200-300', '300-400', '400-500']
    if prob_type == 'ND' and cost == 'degree':
        xtick_labels = ['100-300', '300-500']
    else:
        xtick_labels = ['100-200', '200-300', '300-400', '400-500']
    ys = s[:, :, 0]
    print(ys)
    print(ys[0])
    b_list = []
    for i in range(len(ys)):
        a_list = []
        for j in range(len(ys[i])):
            a_list.append(ys[i][j]/ys[0][j])
        b_list.append(a_list)
    ys = np.array(b_list)

#     ys = np.log10(ys)

#     vs = s[:, :, 1]
    
#     xs = [X, X+0.15, X+0.3, X+0.45, X+0.6, X+0.75, X+0.9, X+1.05]
    if prob_type == 'ND' and cost == 'degree':
        xs = [X, X+0.15, X+0.30, X+0.45, X+0.6, X+0.75, X+0.9, X+1.05]
    else:
        xs = [X, X+0.21, X+0.42, X+0.63, X+0.84, X+1.05, X+1.26, X+1.47]  # 方法间的间隔，以X为基准
    
#     if prob_type == 'CN':
#         xs = [X, X+0.15, X+0.3, X+0.45]
#     else:
#         xs = [X, X+0.15, X+0.3, X+0.45, X+0.6]

    for i in range(len(ys)):
        x, y, c, m = xs[i], ys[i], colors[methods[i]], methods[i]
        Ax.bar(x, y, alpha=0.9, width = width, facecolor = c, label=m) 
#         for xi, yi, vi, in zip(x, y, v):
#             Ax.plot([xi, xi],[yi - vi/2, yi+vi /2],color = 'black')
    if prob_type == 'ND' and cost == 'degree':
        Ax.set_ylim([0/100,700/100])
    else:
        Ax.set_ylim([0/100,150/100])
            
#     if prob_type == 'CN':
#         Ax.set_ylim([10/100,53/100])
#     else:
#         Ax.set_ylim([20/100,64/100])
    legend = Ax.legend(loc='upper right', fontsize=LegendSize, ncol = 2, frameon=True, framealpha=1.0)
    legend.get_frame().set_linewidth(8.0)
    
    if cost == 'unit' and tag == 'a':
        Ax.set_title('Time comparision on BA networks', pad = Labelpad, fontweight='bold', fontsize=subplotTitleSize)
    elif cost == 'unit' and tag == 'c':
        Ax.set_title('Time comparision on SW networks', pad = Labelpad, fontweight='bold', fontsize=subplotTitleSize)
    elif cost == 'degree' and tag == 'b':
        Ax.set_title('Time comparision on PL networks', pad = Labelpad, fontweight='bold', fontsize=subplotTitleSize)
    elif cost == 'degree' and tag == 'd':
        Ax.set_title('Time comparision on Special networks', pad = Labelpad, fontweight='bold', fontsize=subplotTitleSize)
    if cost == 'random':
        Ax.set_title('comparision-Time', pad = Labelpad, fontweight='bold', fontsize=subplotTitleSize)

    Ax.set_xticks(X+0.52)
    Ax.set_xticklabels(xtick_labels, fontsize=TickSize)
    if prob_type == 'ND' and cost == 'degree':
        pass
    else:
        Ax.set_yticks(np.arange(0.0, 1.5, 0.2))

    Ax.set_xlabel('Test Graph Size',labelpad = Labelpad, fontweight='bold', fontsize=TickSize+5)
    if prob_type == 'CN' and cost == 'unit':
        Ax.set_ylabel('Time',labelpad = Labelpad, fontweight='bold', fontsize=TickSize+5)
    elif prob_type == 'ND' and cost == 'unit':
        Ax.set_ylabel('Time',labelpad = Labelpad, fontweight='bold', fontsize=TickSize+5)
    elif prob_type == 'CN' and cost != 'unit':
        Ax.set_ylabel('Time',labelpad = Labelpad, fontweight='bold', fontsize=TickSize+5)
    elif prob_type == 'ND' and cost != 'unit':
        Ax.set_ylabel('Time',labelpad = Labelpad, fontweight='bold', fontsize=TickSize+5)
    
    Ax.text(-0.05, 1.03, '%s'%tag, size=TickSize+25, transform=Ax.transAxes, weight='bold')
    Ax.tick_params(axis='x', labelsize=TickSize, width=5)
    Ax.tick_params(axis='y', labelsize=TickSize, width=5)
    
    Ax.spines['top'].set_linewidth(5)
    Ax.spines['right'].set_linewidth(5)
    Ax.spines['bottom'].set_linewidth(5)
    Ax.spines['left'].set_linewidth(5)

In [ ]:
sns.set('poster', style='ticks')
fig, ax = plt.subplots(2,2, figsize=(78, 62))

############################# synthetic scores
SyntheticBar(ax[0,0], 'CN', cost='unit', tag='a', width=0.2)
SyntheticBar(ax[0,1], 'CN', cost='degree', tag='b', width=0.2)


SyntheticBar(ax[1,0], 'ND', cost='unit', tag='c', width=0.2)
SyntheticBar(ax[1,1], 'ND', cost='degree', tag='d', width=0.1)


fig.tight_layout()
plt.subplots_adjust(wspace = 0.15, hspace =0.22)
plt.show()
fig.savefig('./Figure_2_ndgrl_3.pdf', bbox_inches='tight')


[[2.1700e+00 1.5620e+01 4.9590e+01 1.6537e+02]
 [3.0000e-02 1.0000e-01 3.1000e-01 5.7000e-01]
 [2.0100e+00 9.5500e+00 2.6210e+01 5.4290e+01]
 [2.1000e+00 9.5200e+00 2.6300e+01 5.4350e+01]
 [1.4600e+00 3.6800e+00 7.0900e+00 1.1470e+01]
 [4.0000e-02 1.6000e-01 4.7000e-01 8.7000e-01]
 [5.1000e-01 5.6000e-01 7.3000e-01 1.2300e+00]
 [1.2500e+00 1.5000e+00 1.9700e+00 2.7300e+00]]
[  2.17  15.62  49.59 165.37]
[[3.4800e+00 2.2030e+01 7.0890e+01 1.6085e+02]
 [4.0000e-02 1.4000e-01 3.1000e-01 5.1000e-01]
 [2.4200e+00 1.0260e+01 2.6910e+01 4.8520e+01]
 [2.4500e+00 1.0240e+01 2.7010e+01 4.8410e+01]
 [1.5000e+00 3.9100e+00 7.3000e+00 1.0150e+01]
 [7.0000e-02 2.1000e-01 4.8000e-01 7.6000e-01]
 [6.2000e-01 5.9000e-01 7.8000e-01 1.0600e+00]
 [1.2900e+00 1.5500e+00 2.2400e+00 2.8500e+00]]
[  3.48  22.03  70.89 160.85]
[[2.210e+00 8.590e+00 2.667e+01 5.512e+01]
 [3.000e-02 6.000e-02 1.400e-01 2.100e-01]
 [2.010e+00 8.210e+00 2.233e+01 4.777e+01]
 [2.120e+00 8.640e+00 2.308e+01 5.038e+01]
 [1.470e+00 3.